<a href="https://colab.research.google.com/github/proaro2001/LearningPyTorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor_0 = torch.rand(7,7)
random_tensor_0

tensor([[0.2454, 0.9944, 0.1830, 0.8259, 0.4852, 0.5434, 0.6267],
        [0.7514, 0.1075, 0.6376, 0.8068, 0.1363, 0.8781, 0.2877],
        [0.0841, 0.4416, 0.2599, 0.3985, 0.9585, 0.1865, 0.6073],
        [0.7980, 0.8502, 0.2082, 0.5023, 0.6998, 0.8331, 0.4978],
        [0.5279, 0.2466, 0.7171, 0.7586, 0.6746, 0.9234, 0.8597],
        [0.5930, 0.6024, 0.1867, 0.2389, 0.4685, 0.2604, 0.5682],
        [0.4218, 0.8702, 0.6058, 0.9989, 0.2806, 0.4943, 0.2970]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_1 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(random_tensor_0, random_tensor_1.T)

tensor([[1.7619],
        [1.7617],
        [1.2356],
        [2.3220],
        [2.2099],
        [1.6171],
        [1.6825]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
# Create two random tensors
random_tensor_1 = torch.rand(7,7)
random_tensor_2 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(random_tensor_1, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
random_tensor_3 = torch.rand(2,3).to(device)
random_tensor_4 = torch.rand(size=(2,3)).to(device)
random_tensor_3,random_tensor_4

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(random_tensor_3, random_tensor_4.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print( f"The maximum value of output of 7 is: {torch.max(tensor_C)}")
# Find min
print( f"The minimum value of output of 7 is: {torch.min(tensor_C)}")

The maximum value of output of 7 is: 0.5617256760597229
The minimum value of output of 7 is: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print( f"The index of maximum value from output of 7 is: {torch.argmax(tensor_C)}")

# Find arg min
print( f"The index of minimum value from output of 7 is: {torch.argmin(tensor_C)}")

The index of maximum value from output of 7 is: 3
The index of minimum value from output of 7 is: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_6 = torch.rand(1,1,1,10)


# Remove single dimensions
random_tensor_7 = random_tensor_6.squeeze()

# Print out tensors and their shapes
print( random_tensor_6, random_tensor_6.shape )
print( random_tensor_7, random_tensor_7.shape )

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
